# Generated by Django 3.0.4 on 2020-03-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
